name: test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7']
    steps:
      - name: configure python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: configure node
        uses: actions/setup-node@v1
        with:
            node-version: '10.x'

      - name: install graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz pkg-config libgraphviz-dev
          pip install pygraphviz

      - name: checkout cylc-flow
        uses: actions/checkout@v1
        with:
          reposiory: 'https://github.com/cylc/cylc-flow'
          path: 'cylc-flow'
      - name: install cylc-flow
        run: |
          (cd cylc-flow; pip install -e .[all])

      - name: checkout cylc-doc
        uses: actions/checkout@v1
        with:
          path: 'cylc-doc'
      - name: install cylc-doc
        run: |
          (cd cylc-doc; pip install -e .[all])

      - name: install eslint
        run: |
          npm install -g eslint

      - name: lint
        run: |
          pycodestyle .
          eslint .

      - name: build
        run: |
          make html slides linkcheck SPHINXOPTS='-Wn'

      - name: tutorial suite
        run: |
          mkdir -p "${HOME}/cylc-run"
          bin/run-validate

      - name: debug
        if: failure()
        run: |
          env 
          cat /tmp/sphinx-err*  # sphinx traceback
          find ~/cylc-run -name job.err -exec cat {} +  # cylc error files
